# Test environment variables
env:
  # Test user credentials
  TEST_EMAIL: 'kapil.jain@madgicaltechdom.com'
  TEST_PASSWORD: 'Madgicaltechdom1'
  
  # App configuration
  APP_ID: 'com.kapil.jain.boltexponativewind'
  
  # Expected values
  HOME_SCREEN_TITLE: 'Home'
